#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidApplication12.Resource", IsApplication=true)]

namespace AndroidApplication12
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int button_game_over = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int button_leaderboard = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int button_profile = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int button_save_profile = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int button_score1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button_score10 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button_score100 = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int button_start_gane = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int imageView1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int leaderboard_list = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout3 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int scoreText = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int scrollView1 = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int text_email = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int text_username = 2131034127;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int gameplay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int leaderboard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int profile = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040011
			public const int add_1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int add_10 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int add_100 = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int awesome = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int email = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int game_over = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int leaderboard = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int leaderboard_error = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int loading = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int profile = 2130968579;
			
			// aapt resource value: 0x7f040017
			public const int profile_error_email_invalid = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int profile_error_username_invalid = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int profile_error_username_taken = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int profile_error_username_too_short = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int profile_load_error = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int profile_success = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int profile_success_email_taken = 2130968597;
			
			// aapt resource value: 0x7f04000e
			public const int save_profile = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int score_submit_error = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int score_was_submitted = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int scoreloop = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int start_game = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int submitting_your_score = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int too_bad = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int username = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int your_score = 2130968592;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
